# Environment for ipyparaview with jupyterlab
name: ipy_pv_dev
channels:
  - conda-forge
dependencies:
  - python=3.7.4
  - ipywidgets
  - jupyter
  - jupyterlab
  - nb_conda_kernels
  - ipython
  - pillow
  - paraview
  - nodejs
  - numpy
  - matplotlib
  - pip
  # - pip:
  #     - python-language-server
